# Ansible Inventory for SSM Connection - Generated by Terraform
# This file is dynamically generated. Do not edit manually.

[all:vars]
hs_username = admin
hs_password = ${hs_password}
volume_group_name = ${volume_group_name}
share_name = ${share_name}

[all:children]
clients
storage_servers
ecgroup_nodes
hammerspace

[clients]
%{ for node in clients ~}
${node.private_ip}
%{ endfor ~}

[storage_servers]
%{ for node in storage_servers ~}
${node.private_ip}
%{ endfor ~}

[ecgroup_nodes]
%{ for node in ecgroup_nodes ~}
${node.private_ip}
%{ endfor ~}

[hammerspace]
%{ for node in hammerspace_nodes ~}
${node.private_ip}
%{ endfor ~}
