# Ansible Inventory for SSM Connection - Generated by Terraform
# This file is dynamically generated. Do not edit manually.

[all:children]
clients
storage_servers
ecgroup
hammerspace

[clients]
%{ for ip in clients ~}
${ip}
%{ endfor ~}

[storage_servers]
%{ for ip in storage_servers ~}
${ip}
%{ endfor ~}

[ecgroup_nodes]
%{ for ip in ecgroup_nodes ~}
${ip}
%{ endfor ~}

[hammerspace]
%{ for ip in hammerspace_nodes ~}
${ip}
%{ endfor ~}
