# .github/workflows/terratest-integration.yml
# This workflow runs our Go-based Terratest integration tests.

name: Terratest Integration

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terratest:
    name: Run Terratest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.REGION || 'us-west-2' }}

      - name: Run Terratest Integration Tests
        working-directory: ./test
        run: go test -v -timeout 30m
        env:
          # This env block passes variables from your GitHub repository's settings
          # to Terraform. The TF_VAR_ prefix is a convention that Terratest and
          # Terraform understand automatically.
          TF_VAR_project_name: "terratest-${{ github.run_id }}"
          TF_VAR_vpc_id: ${{ vars.VPC_ID }}
          TF_VAR_subnet_id: ${{ vars.SUBNET_ID }}
          TF_VAR_key_name: ${{ vars.KEY_NAME }}
          TF_VAR_clients_ami: ${{ vars.CLIENTS_AMI }}
          TF_VAR_storage_ami: ${{ vars.STORAGE_AMI }}
          TF_VAR_hammerspace_ami: ${{ vars.HAMMERSPACE_AMI }}
          TF_VAR_ansible_ami: ${{ vars.ANSIBLE_AMI }}
          TF_VAR_share_name: "terratest-share"
          TF_VAR_region: ${{ vars.REGION || 'us-west-2' }}
          
          # Override defaults for a minimal, fast-running test
          TF_VAR_deploy_components: '["clients"]'
          TF_VAR_clients_instance_count: "1"
          TF_VAR_capacity_reservation_create_timeout: "0s"
