# .github/workflows/terratest-integration.yml
# This workflow runs our Go-based Terratest integration tests.

name: Terratest Integration

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        description: "Version tag (i.e. 1.2) for the version to be released"
        type: string
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  terratest:
    name: Run Terratest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.REGION || 'us-west-2' }}

      - name: Run Terratest Integration Tests
        working-directory: ./test
        run: go test -v -timeout 30m
        env:
          # This env block passes variables from your GitHub repository's settings
          # to Terraform. The TF_VAR_ prefix is a convention that Terratest and
          # Terraform understand automatically.
          REGION: ${{ vars.REGION }}
          VPC_ID: ${{ vars.VPC_ID }}
          SUBNET_ID: ${{ vars.SUBNET_ID }}
          KEY_NAME: ${{ vars.KEY_NAME }}
          CLIENTS_AMI: ${{ vars.CLIENTS_AMI }}
          STORAGE_AMI: ${{ vars.STORAGE_AMI }}
